<?php

/**
 * Copyright © Klevu Oy. All rights reserved. See LICENSE.txt for license details.
 */

declare(strict_types=1);

use Klevu\Configuration\Block\Adminhtml\Config\Form\KlevuFieldset;
use Klevu\IndexingApi\ViewModel\Config\Information\IndexingAttributesInterface;

/**
 * @var KlevuFieldset $block
 * @var IndexingAttributesInterface $viewModel
 */
$viewModel = $block->getViewModel();
$escaper = $block->getEscaper();
?>

<?php if ($viewModel->hasAttributes()): ?>
    <h2>
        <strong>
            <?= $escaper->escapeHtml(__('Attributes')->render()) ?>
        </strong>
    </h2>
    <table class="klevu-indexing-attributes">
        <thead>
        <tr>
            <th scope="col"><?= $escaper->escapeHtml(__('API Key')->render()) ?></th>
            <th scope="col"><?= $escaper->escapeHtml(__('Attribute Type')->render()) ?></th>
            <th scope="col"><?= $escaper->escapeHtml(__('Total (Indexable)')->render()) ?></th>
            <th scope="col"><?= $escaper->escapeHtml(__('Add')->render()) ?></th>
            <th scope="col"><?= $escaper->escapeHtml(__('Update')->render()) ?></th>
            <th scope="col"><?= $escaper->escapeHtml(__('Delete')->render()) ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($viewModel->getAttributes() as $apiKey => $attribute): ?>
            <?php foreach ($attribute as $attributeType => $data): ?>
                <tr>
                    <td>
                        <span><?= $escaper->escapeHtml($apiKey) ?></span>
                    </td>
                    <td>
                        <span><?= $escaper->escapeHtml($attributeType) ?></span>
                    </td>
                    <td>
                        <span><?= $escaper->escapeHtml($data['total'] ?? '0') ?></span>
                        <?= '(' . $escaper->escapeHtml($data['indexable'] ?? '0') . ')' ?>
                    </td>
                    <td>
                        <span><?= $escaper->escapeHtml($data['Add'] ?? '0') ?></span>
                    </td>
                    <td>
                        <span><?= $escaper->escapeHtml($data['Update'] ?? '0') ?></span>
                    </td>
                    <td>
                        <span><?= $escaper->escapeHtml($data['Delete'] ?? '0') ?></span>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
        </tbody>
        <tfoot>
        <tr>
            <th scope="row" colspan="6">
                <?= $escaper->escapeHtml(
                    __('Indexing attributes and their next actions.')->render(),
                ) ?>
            </th>
        </tr>
        </tfoot>
    </table>
    <style>
        table.klevu-indexing-attributes {
            table-layout: fixed;
            width: 100%;
            border-collapse: collapse;
            border: solid 1px #f5f5f5;
            background-color: #fff;
            margin-bottom: 30px;
        }

        .klevu-indexing-attributes thead tr,
        .klevu-indexing-attributes tfoot tr {
            border: solid 1px #f5f5f5;
        }

        .klevu-indexing-attributes thead th {
            background-color: #000;
            color: #fff;
            text-align: left;
            border: 0.1rem solid #666666;
        }

        .klevu-indexing-attributes thead th:nth-child(1),
        .klevu-indexing-attributes thead th:nth-child(2) {
            width: 25%;
        }

        .klevu-indexing-attributes tfoot th,
        .klevu-indexing-attributes tr:nth-child(2n) {
            background-color: #fff;
        }

        .klevu-indexing-attributes tr:nth-child(2n-1) {
            background-color: #f5f5f5;
        }

        .klevu-indexing-attributes tbody tr:hover {
            background-color: #e5f7fe;
        }

        .klevu-indexing-attributes tbody td {
            text-align: right;
            border-left: 0.1rem dashed #d6d6d6;
            border-right: 0.1rem dashed #d6d6d6;
        }

        .klevu-indexing-attributes tbody td:nth-child(1),
        .klevu-indexing-attributes tbody td:nth-child(2) {
            text-align: left;
        }

        .accordion .form-inline .config .klevu-indexing-attributes th,
        .accordion .form-inline .config .klevu-indexing-attributes td {
            padding: 1.5rem;
        }
    </style>
<?php endif; ?>
